# Generated by Django 2.0.5 on 2018-05-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('event_description', models.TextField(verbose_name='description of event')),
                ('event_price', models.PositiveIntegerField(verbose_name='price of event')),
                ('event_date', models.DateField(verbose_name='date of event')),
                ('event_time', models.TimeField(verbose_name='time of event')),
                ('event_duration', models.DurationField(verbose_name='duration of event')),
            ],
        ),
    ]
